const employeeData = {
    emp1: {
        id: "emp1",
        name: "Leanne Graham",
        age: 30,
        phoneNumber: 8974045500,
        designation: "Angular Developer",
        score: 8,
    },
    emp2: {
        id: "emp2",
        name: "Ervin Howell",
        age: 37,
        phoneNumber: 7874031010,
        designation: "React Developer",
        score: 9,
    },
    emp3: {
        id: "emp3",
        name: "Chelsey Dietrich",
        age: 41,
        phoneNumber: 8974031047,
        designation: "Angular Developer",
        score: 7,
    },
    emp4: {
        id: "emp4",
        name: "Dennis Schulist",
        age: 26,
        phoneNumber: 9057831089,
        designation: "Vue Developer",
        score: 7,
    },
    emp5: {
        id: "emp5",
        name: "Kurtis Weissnat",
        age: 29,
        phoneNumber: 8977891080,
        designation: "NodeJs Developer",
        score: 6,
    },
    emp6: {
        id: "emp6",
        name: "Glenna Reichert",
        age: 29,
        phoneNumber: 8977891080,
        designation: "Angular Developer",
        score: 8,
    },
    emp7: {
        id: "emp7",
        name: "John Smith",
        age: 29,
        phoneNumber: 8977891080,
        designation: "NodeJs Developer",
        score: 10,
    },
    emp8: {
        id: "emp8",
        name: "Vikas M",
        age: 29,
        phoneNumber: 8977891080,
        designation: "NodeJs Developer",
        score: 8,
    },
    emp9: {
        id: "emp9",
        name: "Amarpreet Singh",
        age: 29,
        phoneNumber: 8977891080,
        designation: "NodeJs Developer",
        score: 9,
    },
    keys: [
        "emp1",
        "emp2",
        "emp3",
        "emp4",
        "emp5",
        "emp6",
        "emp7",
        "emp8",
        "emp9",
    ],
};

module.exports = employeeData;
